baseURL = "https://shlason.github.io/"
languageCode = "zh-th"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false
theme = "PaperMod"
title = "Shlason's blog"
pagination.pagerSize = 10